FROM quay.io/podman/stable as tools
ARG KUBECTX_VERSION=v0.9.5
ARG K9S_VERSION=v0.27.4

ADD https://github.com/ahmetb/kubectx/releases/download/${KUBECTX_VERSION}/kubectx_${KUBECTX_VERSION}_linux_x86_64.tar.gz /opt
ADD https://github.com/ahmetb/kubectx/releases/download/${KUBECTX_VERSION}/kubens_${KUBECTX_VERSION}_linux_x86_64.tar.gz /opt
ADD https://github.com/derailed/k9s/releases/download/${K9S_VERSION}/k9s_Linux_amd64.tar.gz /opt

RUN tar -xzvf /opt/kubectx_${KUBECTX_VERSION}_linux_x86_64.tar.gz -C /opt \
    && tar -xzvf /opt/kubens_${KUBECTX_VERSION}_linux_x86_64.tar.gz -C /opt \
    && tar -xzvf /opt/k9s_Linux_amd64.tar.gz -C /opt \
    ;


FROM quay.io/podman/stable
# Install some useful CLI utilities (ncurses provide "clear", vim is our
# editor of choice and shellinabox is required to provide a in-browser-terminal experience)

COPY --from=tools /opt/kubectx /usr/local/bin
COPY --from=tools /opt/kubens /usr/local/bin
COPY --from=tools /opt/k9s /usr/local/bin

RUN dnf -y update \
 && dnf -y install jq ncurses shellinabox vim less \
 && dnf clean all

RUN echo 'export PS1="\w \$ "' >> /root/.bashrc
RUN echo "set bg=dark" > /root/.vimrc

# install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && mv kubectl /usr/bin/kubectl \
    && chmod +x /usr/bin/kubectl \
    ;

# install kubectx/kubens

#RUN usermod --add-subuids 200000-201000 --add-subgids 200000-201000 root

ADD styles.css /data/

EXPOSE 4200

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CMD ["shellinaboxd", "--css", "/data/styles.css", "-s", "/:0:0:/root:/bin/bash", "--disable-ssl"]
