version: "3.8"

services:

  reveal:
    image: docker.io/webpronl/reveal-md:5.5.1
    privileged: false
    cpus: 0.5
    ports:
      - "8123:1948"
    volumes:
      - ${PWD}/presentation:/slides:Z
    command:
    - /slides
    - --theme="theme.css"
    - --port="1948"
    - --title="Workshop"
    - --watch
    - --disable-auto-open
    init: true
    labels: {}

  shell:
    image: localhost/shellinabox:latest
    cpus: 0.5
    volumes:
      - ./examples:/root/examples:Z
      - $HOME/.kube/config:/root/.kube/config:ro
    build:
      context: ./shells/shellinabox1
      dockerfile: Containerfile
    privileged: true
    network_mode: host
    labels: {}
