version: "3.8"

services:

  reveal:
    image: docker.io/webpronl/reveal-md:5.5.2
    privileged: false
    cpus: 0.5
    ports:
      - "35729:35729" # Live-reload
      - "8123:1948"   # HTTP contents
    volumes:
      - ${PWD}/workshops/${WORKSHOP:-kubernetes}:/slides:Z
    command:
    - /slides
    - --theme="theme.css"
    - --port="1948"
    - --title="Workshop"
    - --watch
    - --disable-auto-open
    init: true
    labels: {}

  shell:
    image: localhost/shellinabox:latest
    cpus: 0.5
    volumes:
      - ./workshops/kubernetes/examples:/root/examples:Z
      - $HOME/.kube/config:/root/.kube/config:rw
    build:
      context: ./shell
      dockerfile: Containerfile
    privileged: true
    network_mode: host
    labels: {}
