version: "2.2"

services:
  reveal:
    build: .
    ports:
      - "127.0.0.1:8123:1948"
    volumes:
      - ${PWD}/presentation:/reveal
    init: true
  shell_0: &build
    image: local/shellinabox
    volumes:
      - ./examples:/root/examples
    build:
      context: shells/shellinabox1
    ports:
      - "127.0.0.1:42000:4200"
