version: "2.2"

services:

  reveal:
    build: .
    ports:
      - "127.0.0.1:8123:1948"
    volumes:
      - ${PWD}/presentation:/reveal
    init: true

  shell_1:
    build: shells/shellinabox1
    ports:
      - "127.0.0.1:4200:4200"
    privileged: true
    volumes:
      - ${HOME}/.docker/machine/machines/vbox-test:/root/.docker/machine/machines/vbox-test:ro

  docker:
    image: docker:dind
    privileged: true

