FROM quay.io/podman/stable

RUN dnf -y update \
 && dnf -y install curl vim shellinabox \
 && dnf clean all

RUN echo 'export PS1="\w \$ "' >> /root/.bashrc
RUN echo "set bg=dark" > /root/.vimrc

#RUN usermod --add-subuids 200000-201000 --add-subgids 200000-201000 root

ADD styles.css /data/

COPY dbash /usr/local/bin/dbash

EXPOSE 4200

CMD ["shellinaboxd", "--css", "/data/styles.css", "-s", "/:0:0:/root:/usr/local/bin/dbash", "--disable-ssl"]
