FROM quay.io/podman/stable

# Install some useful CLI utilities (ncurses provide "clear", vim is our
# editor of choice and shellinabox is required to provide a in-browser-terminal experience)
RUN dnf -y update \
 && dnf -y install jq ncurses shellinabox vim \
 && dnf clean all

RUN echo 'export PS1="\w \$ "' >> /root/.bashrc
RUN echo "set bg=dark" > /root/.vimrc

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN mv kubectl /usr/bin/kubectl
RUN chmod +x /usr/bin/kubectl

#RUN usermod --add-subuids 200000-201000 --add-subgids 200000-201000 root

ADD styles.css /data/

COPY dbash /usr/local/bin/dbash

EXPOSE 4200

CMD ["shellinaboxd", "--css", "/data/styles.css", "-s", "/:0:0:/root:/usr/local/bin/dbash", "--disable-ssl"]
