---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    part-of: qvest-kube-workshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      part-of: qvest-kube-workshop
  template:
    metadata:
      labels:
        app: nginx
        part-of: qvest-kube-workshop
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

