---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-server
  labels:
    component: webserver
    app: gitea
    part-of: qvest-kube-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea-server
      component: webserver
      app: gitea
      part-of: qvest-kube-workshop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea-server
        component: webserver
        app: gitea
        part-of: qvest-kube-workshop
    spec:
      containers:
      - name: gitea
        image: docker.io/gitea/gitea:latest