---
apiVersion: v1
kind: Pod
metadata:
  name: gitea-database
  labels:
    part-of: qvest-kube-workshop
    app: gitea
    component: database
spec:
  containers:
  - name: database
    image: docker.io/postgres:latest
    env:
      - name: POSTGRES_PASSWORD
        value: postgres
