---
apiVersion: v1
kind: Pod
metadata:
  name: gitea-server
  labels:
    part-of: qvest-kube-workshop
    app: gitea
    component: webserver
spec:
  containers:
  - name: gitea
    image: docker.io/gitea/gitea:1.21.1
