---
apiVersion: v1
kind: Pod
metadata:
  name: gitea
  labels:
    app: gitea
    component: server
spec:
  containers:
  - name: gitea
    image: docker.io/gitea/gitea:latest
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  type: NodePort
  selector:
    app: gitea
    component: server
  ports:
  - port: 9999
    targetPort: 3000
