apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-server
  labels:
    version: "1.20"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea-server
    spec:
      containers:
      - name: gitea
        image: docker.io/gitea/gitea:1.20
