version: '2'
services:

  telegraf:
    image: telegraf
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/rootfs/proc:ro
      - /sys:/rootfs/sys:ro
      - /etc:/rootfs/etc:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

    grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    labels:
      - "traefik.backend=grafana"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=PathPrefixStrip:/grafana;Host: chat.network-innovation.de"
      - "traefik.docker.network=traefik_webgateway"
    networks:
      - default
      - web

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_ADMIN_USER=monitoring
      - INFLUXDB_ADMIN_PASSWORD=grn89e73
    volumes:
      - ./data/influxdb:/var/lib/influxdb

networks:
  web:
    external:
      name: traefik_webgateway

