---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitea-server-lb
    component: load-balancer
    part-of: qvest-kube-workshop
  name: gitea-server-lb
spec:
  type: LoadBalancer
  selector:
    app: gitea-server
  ports:
  - targetPort: 3000
    port: 3000
...
