---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-database
  labels:
    app: gitea-database
    part-of: qvest-kube-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-database
  serviceName: gitea-database-headless
  template:
    metadata:
      labels:
        app: gitea-database
    spec:
      containers:
      - name: mariadb
        image: docker.io/library/mariadb:11.1.3
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_RANDOM_ROOT_PASSWORD
          value: "true"

        # Specify the database name, user and password using a secret.
        # See https://hub.docker.com/_/mariadb for the environment variables
        # that can be used.
        envFrom: [] # << Replace with actual reference to secret
...
