---
apiVersion: v1
kind: Service
metadata:
  name: gitea-database-headless
  labels:
    headless: "true"
    part-of: qvest-kube-workshop
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3336
      targetPort: 3306
  selector:
    app: gitea-database
...
