---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-database-config
type: Opaque
stringData:
  # Should be mapped to MARIADB_USER / GITEA__database__USER
  MARIADB_USER: gitea
  # Should be mapped to MARIADB_DATABASE / GITEA__database__NAME
  MARIADB_DATABASE: gitea
  # Should be mapped to MARIADB_PASSWORD / GITEA__database__PASSWD
  MARIADB_PASSWORD: "sn!Xp9Fts12L%tFfc" # Just a bunch of random characters.

...
