---
apiVersion: v1
kind: Service
metadata:
  name: gitea-database
  labels:
    part-of: qvest-kube-workshop
spec:
  ports:
    - port: 3336
      targetPort: 3306
  selector:
    app: gitea-database
...
