---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-server
  labels:
    app: gitea-server
    part-of: qvest-kube-workshop
spec:
  selector:
    matchLabels:
      app: gitea-server
  template:
    metadata:
      labels:
        app: gitea-server
    spec:
      containers:
      - name: gitea
        image: docker.io/gitea/gitea:1.21.1
        env:
        - name: GITEA__security__INSTALL_LOCK
          value: "false" # Set this to "true" once everything else works.
        - name: GITEA__database__DB_TYPE
          value: mysql
        - name: GITEA__database__HOST
          value: gitea-database
      # Set the environment variable GITEA__database__PASSWD using the value that has been stored
      # within the secret
