---
apiVersion: v1
kind: Pod
metadata:
  name: gitea-server
  labels:
    part-of: qvest-kube-workshop
spec:
  containers:
  - name: gitea
    image: docker.io/gitea/gitea:1.21.1
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
  volumes:
  - name: configuration
    configMap:
      name: gitea-config-files # Must match metadata.name of the referenced configMap
...
