---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-server
  labels:
    app: gitea-server
    part-of: qvest-kube-workshop
spec:
  selector:
    matchLabels:
      app: gitea-server
  template:
    metadata:
      labels:
        app: gitea-server
    spec:
      containers:
      - name: gitea
        image: docker.io/gitea/gitea:1.21.1
      volumes:
      - name: configuration
        configMap:
          name: gitea-config-files # Must match metadata.name of the referenced configMap